### ISSUE TITLE
too large maximum depth value

### ISSUE THREAD

**Issue by afpapqy** [enric1994/synth-colon#1]
Hi, thanks for your great work.
I tried to use the depth dataset you generated, but I found that many of them have a maximum depth value of 99999999...
These depth maps have some depth inconsistency in the visualized graph, as the image you show on the main page which has a yellow region on the top-left representing the abnormal values (https://github.com/enric1994/synth-colon/blob/master/images/depth.png).
I wonder how that was generated and how should I correct that if I want to use your depth dataset for training proposes.

**Comment by enric1994** [comment]
Hello! Thanks for pointing this out. There is a part of some depth images that shows the background in the corner. I used Blender to generate it, the script is [here](https://github.com/enric1994/synth-colon/blob/master/synth/src/generate.py).

I don't have access to my server right now, but I will try to generate a new version of the dataset soon.

If you are interested in the dataset, perhaps you will find my latest dataset useful: [video-colon](https://github.com/enric1994/video-colon)

**Comment by afpapqy** [comment]
> Hello! Thanks for pointing this out. There is a part of some depth images that shows the background in the corner. I used Blender to generate it, the script is [here](https://github.com/enric1994/synth-colon/blob/master/synth/src/generate.py).
> 
> I don't have access to my server right now, but I will try to generate a new version of the dataset soon.
> 
> If you are interested in the dataset, perhaps you will find my latest dataset useful: [video-colon](https://github.com/enric1994/video-colon)

Thanks for your quick reply. Maybe I can crop out the abnormal areas. 
In addition, I noticed that the size of the triangular patches that divide the intestinal wall into your data set is still relatively large. Do you have any quick way to modify it to be more detailed? 
My graphics foundation is not good, so it would be best if I could produce more precise results by modifying and running uncomplicated code.

**Comment by enric1994** [comment]
Sorry but I'm still locked out of my server at the moment. Here's what you could do to keep things moving forward.

You could create your own custom dataset. Just run `docker-compose up -d synth-polyp`. Then run `docker exec synth-polyp python ./synth/src/generate.py --name test_dataset --size 10`. This command will produce 10 images you can use for debugging.

Now you could try changing the `generate.py`:

1. **Remove empty corners**: 
   - You can make the colon model a bit bigger to fix that. [Tweak the model size here](https://github.com/enric1994/synth-colon/blob/master/synth/src/generate.py#L38-L39). Maybe try setting `b.scale[0]` and `b.scale[1]` up to 4.5.

2. **Smooth surfaces**: 
   - If the colon surface is looking too "flat", you're going to want to reduce `long_interval` and add more points to `pts=[...]` [here](https://github.com/enric1994/synth-colon/blob/master/synth/src/generate.py#L56). It may take a few attempts to generate the right smoothness.

After you've generated some new images, you'll find a Blender file saved as `/synth-polyp/scene.blend`. Definitely worth opening it up to check out the 3D model. It's a great way to understand what's going on and helps with making the right tweaks.
